### ISSUE TITLE
Disable Unimus components

### ISSUE THREAD

**Issue by Kiekeboe100** [crocandr/docker-unimus#22] opened 2024-06-26 10:06 UTC
Hello,

I've change the JAVA_OPTS in the docker compose file.
      - JAVA_OPTS=-Xms256M -Xmx1024M -Dunimus.core.discovery-disabled=true -Dunimus.core.push-disabled=true -Dunimus.core.scan-disabled=true

But those disabled component are still visible in the gui.

regards,
Stijn

**Comment by crocandr** [comment] 2024-07-01 18:38
Hi,

I have tried some of these options that you mention:
https://wiki.unimus.net/display/UNPUB/Disabling+specific+Unimus+features
I think these are little bit tricky but works :)

If I used "-Dunimus.core.scan-disabled=true" option, the scan menu still available on the WebUI!
The scan has run very quickly, but the list is empty. (check the image below).
![network-scan-disabled](https://github.com/crocandr/docker-unimus/assets/7159285/25047699-084b-4fc5-9cc4-987edeebeb42)
If I used the default (enabled) function, the scan was slowest and the list contained lots of network devices.
![network-scan-enabled](https://github.com/crocandr/docker-unimus/assets/7159285/c80fb90f-97d4-4af7-a271-5e2848ff7bbd)


If I used "-Dunimus.core.discovery-disabled=true" option, the discovery option at the device shows the option is denied and not worked.
![discovery-disabled](https://github.com/crocandr/docker-unimus/assets/7159285/2ad291f7-258e-428a-a922-7df51c61ebf9)
If I used the default (enabled) option, the discovery was run, but I don't have any Mikrotik or compatible network device now, so not was successful, but worked :)
![discovery-enabled](https://github.com/crocandr/docker-unimus/assets/7159285/a653d77c-4f51-44b0-af83-a02662f64991)


The PS output from my docker server:
With disabled options:
```# ps -ef | grep -i java
root     1230512 1230507 12 20:13 ?        00:02:13 java -Xms256M -Xmx1024M -Dunimus.core.connect-timeout=20000 -Dunimus.core.inter-connection-delay=1000 -Dunimus.core.cli-expect-timeout=30000 -Dunimus.core.scan-disabled=true -Dunimus.core.discovery-disabled=true -jar /opt/unimus.jar
```
Default options:
```# ps -ef | grep -i java
root     1247458 1247453 48 20:32 ?        00:02:06 java -Xms256M -Xmx1024M -Dunimus.core.connect-timeout=20000 -Dunimus.core.inter-connection-delay=1000 -Dunimus.core.cli-expect-timeout=30000 -jar /opt/unimus.jar
```

I think these options work like as designed by developer company, so I close this ticket.

**Closed as completed** 2024-07-01 18:38 UTC

**Comment by tomaskir** [comment] 2024-07-03 22:23
@XiteHosting - the functionality to disable these features works, but indeed you won't see it in the web UI.

These settings disable the specific job type in the Core:
https://wiki.unimus.net/display/UNPUB/Architecture+overview

Since you can have many remote Cores, this function can be used to for example disable some features in a particular Zone. BUT since you can have this Disabled / Enabled differently in different Zones, the function doesn't affect the UI. It would be very messy to deal with this in the UI when you can select devices whose core support this, when Cores are offline (so you don't know if the Core allows this feature), etc.

As you can see in pictures by @crocandr, when these are disabled, you will get a message like `Operation denied by Core` on devices whose Core has this disabled.
